FROM python:3.11-slim

WORKDIR /app

# Install Poetry
RUN pip install poetry

# Copy dependency files
COPY pyproject.toml poetry.lock* ./

# Install dependencies
RUN poetry config virtualenvs.create false \
    && poetry install --only main --no-root --no-interaction --no-ansi

COPY src/fritz_monitoring/log_pusher.py .

ENV PYTHONUNBUFFERED=1

CMD ["poetry", "run", "python", "log_pusher.py"]
