FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/fritz_monitoring/log_pusher.py ./

ENV PYTHONUNBUFFERED=1

CMD ["python", "log_pusher.py"]
