apiVersion: 1

datasources:
  - name: Network Graph JSON
    type: yesoreyeram-infinity-datasource
    access: proxy
    url: http://fritz_exporter:8000
    isDefault: false
    jsonData:
      tlsSkipVerify: true
    editable: true
